# Generated by Django 3.2.10 on 2021-12-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bills_products',
            options={'ordering': ['id']},
        ),
    ]
